### ISSUE TITLE
Depreciation of python packages and .yml issues

### ISSUE THREAD

**Issue by JelleLagerweij** [kjappelbaum/ml_molsim2020#26]
Dear developer,
I am preparing for the MolSim2024 course in Amsterdam. For this, I needed to:

- [x] install *wsl* (and a lot of compiler options with VScode)
- [x] create a conda env for *OPS*
- [x] create a conda env for *ml_molsim* 

I completed all tasks successfully, however, I did have some slight setbacks when creating the *ml_molsim* conda environment, which I will go into below. 

Foremost, when executing `conda env create -f environment.yml -n ml_molsim` command, the installation crashed. It surprised me because I was using a clean *wsl* with a clean conda install. I forgot to document and save the error report (it would have made creating this issue much cleaner), but I solved it by looking at a similar issue online: [https://github.com/DeepLabCut/DeepLabCut/issues/2322](https://github.com/DeepLabCut/DeepLabCut/issues/2322). In the end, it had something to do with the `nb_conda` package and how it works together with current `notebook` versions. I adjusted this in the *environment.yml* by limiting the version of the notebook package (see below). After this, the installment procedure worked without issues.

An additional issue occurred only after I tried to run the *molsim_ml.ipynb* file. It crashed in the first relevant code block (under Import package we need). Again, I forgot to save my own error output, however this post solved my issues: [https://pypi.org/project/pandas-profiling/](https://pypi.org/project/pandas-profiling/). If I understand correctly, the package `pandas-profiling` is renamed to `ydata-profiling`. I adjusted this in the *environment.yml* as well (see below). This would however also need changes in the jupyter notebook and python files. I think that all issues would be resolved if the original *environment.yml* file would contain version numbers. This would at least make the environment more robust.

### Renewed  environment.yml file
```yml
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - ydata-profiling
  - ipywidgets
  - hyperopt
  - kaggle
  - plotly
  - scikit-learn
  - scipy
  - numpy
  - python
  - py-xgboost
  - jupyterlab
  - nb_conda
  - notebook<7.0.0
  - bokeh
  - pandas
  - holoviews
  - seaborn
````
